# What we should put in front of each blog URL
blog_prefix_path: "blog"

# Where to write the static html output
output_path: "output"

posts_path: "content"

pages_path: "pages"

create_index_for:
  - fr
  - en

markdown:
  highlight_code: true

# Copy everything in this directory to the output directory
static_path: "static"
